name: train_simulator_client
description: A client for accessing Train Simulator.
version: 0.6.0
homepage: https://github.com/tnc1997/dart-train-simulator-client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
  xml: ^6.0.0
  xml_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  test: ^1.16.0
  xml_serializable: ^2.0.0
