name: train_simulator_client
description: A client for accessing Train Simulator.
version: 0.5.0
homepage: https://github.com/tnc1997/dart-train-simulator-client

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety
  path: ^1.8.0-nullsafety
  xml: ^5.0.0-nullsafety
  xml_annotation: ^2.0.0-nullsafety

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
  xml_serializable: ^2.0.0-nullsafety
