name: train_simulator_client
description: A starting point for Dart libraries or applications.
version: 0.3.0
homepage: https://github.com/tnc1997/dart-train-simulator-client

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  path: ^1.0.0
  xml: ^4.0.0
  xml_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
  xml_serializable: ^1.0.0
